### ISSUE TITLE
Konsumen dapat melakukan pemesanan & review

### ISSUE THREAD

**Issue by rizalw** [SI-RPL-2022/SI4308_B_CLOTHZEE#1]

**Comment by Iqballlfw** [comment]
<h1 class="text-align: center;">&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; ini tampilan pemesanan</h1>

![Pesan konfeksi](https://user-images.githubusercontent.com/92244937/162578542-8a26aefc-96e8-47ba-b141-b7e4aa4ec529.png)

**Comment by randikasta** [comment]
https://www.figma.com/file/JRR9xj2vg0QG9UPdcm8P5X/Kelompok-Budaya-team-library?node-id=470%3A229

Ini tampilan gambaran kasar bagian konsumen dapat melakukan pemesanan & review
